### PR TITLE
Added max_phase as an option

### PR DESCRIPTION
**Pull request by jhylin**
This PR is related to this issue [#1](https://github.com/jhylin/Data_in_life_blog/issues/1), many thanks.

### CODE REVIEW

**Review by jhylin — COMMENTED** [review]
Oops yes, that was acting like a filter, I've changed it into a boolean flag (leaving it as False as default, and can be toggled on if set to True), and added it into the string code section, and also the actual SQL part. Is this better?

**Comment by cthoyt** [comment]
@jhylin yes! I made a minor update in 72cd48a but this should do it. Did you test it works locally?

**Comment by jhylin** [comment]
Yes, I just did a unittest on the latest code (I've pushed the test_queries.py in the /test folder), and it worked. The only thing was (very likely due to my lack of experience in doing unittest), I had to temporarily make target_id as Optional[str], and the test passed - unsure how I would resolve the error message regarding "missing 1 positional statement for target_id" in the unittest if I didn't make it optional?

**Comment by cthoyt** [comment]
@jhylin the trick was that you were missing the `target_id` argument - you just had to pass a string. I did a bit of re-org and merged this. Thanks! Will make a release momentarily.

**Pull request merged**
